PAO_dict_list = {

    0: ("Suess", "Eating", "Green Eggs"),
    1: ("Sid", "Torturing", "Woody"),
    2: ("Sinai", "Burning", "Bush"),
    3: ("Sumo", "Crushing", "Chair"),
    4: ("Ezra", "Building", "Wall"),
    5: ("Saul", "Stoning", "Stephen"),
    6: ("Sage", "Brewing", "Potions"),
    7: ("Sequoia", "Growing", "California"),
    8: ("Sophie", "Scattering", "Pamphlets"),
    9: ("Sub", "Diving", "Mariana Trench"),
    10: ("Tesla", "Inventing", "Electric Chair"),
    11: ("Dodo", "Waddling", "Zoo"),
    12: ("Danny", "Playing", "Tennis"),
    13: ("Tamra", "Organizing", "Kitchen"),
    14: ("T-Rex", "Devouring", "Lawyer"),
    15: ("Doula", "Delivering", "Baby"),
    16: ("DJ", "Dancing", "Disco Ball"),
    17: ("Duck", "Quacking", "Pond"),
    18: ("Davinci", "Painting", "Mona Lisa"),
    19: ("TB", "Infecting", "Ramunajan"),
    20: ("Nessie", "Hiding", "Lochness"),
    21: ("Newt", "Poisoning", "Heron"),
    22: ("Nun", "Feeding", "Beggar"),
    23: ("Nemo", "Losing", "Marlin"),
    24: ("Nero", "Ruling", "Rome"),
    25: ("Nellie", "Bullying", "Laura"), 
    26: ("Nachos", "Dipping", "Jalapeno Sauce"),
    27: ("Neck", "Hanging", "Noose"),
    28: ("Knife", "Cutting", "Bamboo"),
    29: ("Honeybees", "Swarming", "Hive"),
    30: ("Mouse", "Caught", "Trap"),
    31: ("Matthew", "Collecting", "Taxes"),
    32: ("Mine", "Exploding", "Tank"),
    33: ("Mummy", "Haunting", "Pyramid"),
    34: ("Mirror", "Reflecting", "Evil Queen"), #mario, , ground pound
    35: ("Mole", "Burrowing", "Hole"),
    36: ("Match", "Lighting", "Campfire"),
    37: ("Macaw", "Flying", "Rainbow"),
    38: ("Murph", "Solving", "Gravity"),
    39: ("Amoeba", "Engulfing", "Enterprise"),
    40: ("Rose", "Pricking", "Grandma"),
    41: ("Rat", "Swimming", "Sewer"),
    42: ("Rhino", "Ramming", "Truck"),
    43: ("Ram", "Climbing", "Cliff"),
    44: ("Harrier", "Ascending", "Carrier"),
    45: ("Oriole", "Chirping", "Meadow"),
    46: ("Roach", "Scurrying", "Toilet"),
    47: ("Orca", "Hunting", "Seal"),
    48: ("Rover", "Landing", "Mars"),
    49: ("Ruby", "Glistening", "Treasure Chest"),
    50: ("Lizard", "Sticking", "Wall"),
    51: ("Lute", "Strumming", "Song"),
    52: ("Alien", "Piloting", "Flying Saucer"),
    53: ("Llama", "Spitting", "Tourist"),
    54: ("Larry", "Waltzing", "Tomatoes"),
    55: ("Lilac", "Blooming", "Green Gables"),
    56: ("Leech", "Sucking", "Blood"), 
    57: ("Hulk", "Smashing", "Loki"), #alligator, "luke,", something..., "lightsaber" --> actually it's Loki he smashes...
    58: ("Elvis", "Shaking", "Hips"),
    59: ("Lips", "Kissing", "Frog"),
    60: ("Cheese", "Melting", "Pizza"),
    61: ("Cheetah", "Racing", "Usain Bolt"),
    62: ("Genie", "Crammed", "Bottle"),
    63: ("Jam", "Spreading", "Toast"),
    64: ("Cherry", "Powering Up", "Pac-Man"),
    65: ("Shield", "Blocking", "Arrows"),
    66: ("Joshua", "Conquering", "Canaan"),
    67: ("Chick", "Peeping", "Mother Hen"),
    68: ("Chef", "Sauteeing", "Onions"),
    69: ("Ship", "Cruising", "Bahamas"),
    70: ("Goose", "Laying", "Golden Egg"),
    71: ("Coyote", "Howling", "Moon"),
    72: ("Gun", "Shooting", "Target"),
    73: ("Gum", "Sticking", "Shoe"),
    74: ("Okra", "Frying", "Batter"), #oil, not batter?
    75: ("Goalie", "Skating", "Ice Rink"),
    76: ("Kim Jong Un", "Launching", "Missile"),
    77: ("King Kong", "Beating", "Chest"),
    78: ("Coffee", "Spilling", "Laptop"),
    79: ("Cowboy", "Herding", "Cattle"),
    80: ("Phaser", "Vaporizing", "Scottie"),
    81: ("Aphid", "Festering", "Houseplant"),
    82: ("Phoenix", "Rising", "Ashes"),
    83: ("Femur", "X-rayed", "Doctor"),
    84: ("Pharoah", "Riding", "Chariot"),
    85: ("Foal", "Stumbling", "Barn"),
    86: ("Fish", "Caught", "Net"),
    87: ("Fig", "Rotting", "Ground"),
    88: ("Fife", "Incarcerating", "Otis"),
    89: ("Viper", "Striking", "Snake Charmer"),
    90: ("Paws", "Printing", "Plaster of Paris"),
    91: ("Bat", "Echolocating", "Moth"),
    92: ("Panda", "Mastering", "Kung Fu"),
    93: ("Puma", "Stalking", "Biker"),
    94: ("Bear", "Hibernating", "Cave"),
    95: ("Polio", "Crippling", "FDR"),
    96: ("Pitcher", "Throwing", "Fastball"),
    97: ("Pig", "Wallowing", "Mud"),
    98: ("Beaver", "Gnawing", "Tree"),
    99: ("Pope", "Preaching", "Cathedral"),
}

alternates = {
    #oriale singing instead of chirping
    #alien piloting UFO or flying saucer
    #nile turning/changing to blood
    None
}

singles = {

    0: ("donut"),
    1: ("candle"),
    2: ("swan"),
    3: ("handcuffs"),
    4: ("sailboat"),
    5: ("snake"),
    6: ("elephant"),
    7: ("boomerang"),
    8: ("snowman"),
    9: ("balloon"),
}

#my_dict = {"name": "Alice", "age": 30, "city": "New York"}